/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import ca.odell.glazedlists.BasicEventList;
import ca.odell.glazedlists.EventList;
import ca.odell.glazedlists.swing.GlazedListsSwing;
import classes.Cliente;
import classes.Quarto;
import dao.ClienteDAO;
import dao.DAOFactory;
import gui.glazed.ClienteTableFormat;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class JFrameCliente extends javax.swing.JFrame {
    
    private EventList<Cliente> clientes = new BasicEventList<>();
    private JDialogCadastroCliente janela;
    private DAOFactory fabrica;
    private Quarto quarto;
    /**
     * Creates new form JFramePrincipal
     */
    public JFrameCliente() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagens/icone.png")));
        janela = new JDialogCadastroCliente(this, true);
        //JOptionPane.showMessageDialog(this, "Criado frame cliente sem quarto!");
        fabrica= new DAOFactory();
        fabrica.abrirConexao();
        ClienteDAO dao = fabrica.criarClienteDAO();
        
        clientes.addAll(dao.buscarTodos());
                
        fabrica.fecharConexao();
    }
    
    //Recebe o quarto para retornar ao entrada de hospede
    public JFrameCliente(Quarto quarto) {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagens/icone.png")));
        //JOptionPane.showMessageDialog(this, "Criado frame cliente com quarto!");
        this.quarto = quarto;
        janela = new JDialogCadastroCliente(this, true);
        fabrica= new DAOFactory();
        fabrica.abrirConexao();
        ClienteDAO dao = fabrica.criarClienteDAO();
        
        clientes.addAll(dao.buscarTodos());
                
        fabrica.fecharConexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonNovo = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonRemover = new javax.swing.JButton();
        jTextFieldBusca = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jButtonAdicionar = new javax.swing.JButton();

        setTitle("Controle Cliente");
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTable1.setModel(GlazedListsSwing.eventTableModel(clientes, new ClienteTableFormat()));
        jScrollPane1.setViewportView(jTable1);

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonAlterar.setText("Alterar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButtonRemover.setText("Remover");
        jButtonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverActionPerformed(evt);
            }
        });

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jButtonAdicionar.setText("Adicionar ao Quarto");
        jButtonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButtonNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonRemover)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAdicionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonBuscar))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonAlterar, jButtonBuscar, jButtonNovo, jButtonRemover});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNovo)
                    .addComponent(jButtonAlterar)
                    .addComponent(jButtonRemover)
                    .addComponent(jTextFieldBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar)
                    .addComponent(jButtonAdicionar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        int resposta = janela.mostrarNovo();
        
        if(resposta == JDialogCadastroCliente.OK){
            Cliente cliente = janela.getCliente();
            fabrica.abrirConexao();
            ClienteDAO dao = fabrica.criarClienteDAO();
            dao.gravar(cliente);
            fabrica.fecharConexao();
            buscarTodos();
        }
    }//GEN-LAST:event_jButtonNovoActionPerformed
    public EventList<Cliente> getClientes(){
        return clientes;
    }
    
    //Retorna o cliente selecionado
    public Cliente getSelectedCliente(){
        int linha = jTable1.getSelectedRow();
        if(linha != -1){
            Cliente cliente = clientes.get(linha);
            return cliente;
        }
        return null;
    }
    
    private void jButtonRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverActionPerformed
        int linha = jTable1.getSelectedRow();
        if(linha != -1){
            Cliente cliente = clientes.get(linha);
            fabrica.abrirConexao();
            ClienteDAO dao = fabrica.criarClienteDAO();
            dao.remover(cliente);
            fabrica.fecharConexao();
            buscarTodos();
        }
    }//GEN-LAST:event_jButtonRemoverActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        int linha = jTable1.getSelectedRow();
        if(linha != -1){
            Cliente cliente = clientes.get(linha);
            
            int resposta  = janela.mostrarAlterar(cliente);
            if(resposta == JDialogCadastroCliente.OK){
                fabrica.abrirConexao();
                ClienteDAO dao = fabrica.criarClienteDAO();
                dao.atualizar(janela.getCliente());
                fabrica.fecharConexao();
                buscarTodos();
            }   
        }
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        if(!jTextFieldBusca.getText().isEmpty()){
            fabrica.abrirConexao();
            ClienteDAO dao = fabrica.criarClienteDAO();
            clientes.clear();
            clientes.addAll(dao.buscar(jTextFieldBusca.getText()));
            fabrica.fecharConexao();
        }else{
            buscarTodos();
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    public Cliente adicionarCliente(){
        setVisible(true);
        return getSelectedCliente();
    }
    private void jButtonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButtonAdicionarActionPerformed

    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing

//    public Cliente adicionarAoQuarto(Quarto quarto){
//        int linha = jTable1.getSelectedRow();
//        if(linha != -1){
//            Cliente cliente = clientes.get(linha);
//            cliente.set
//            fabrica.abrirConexao();
//            ClienteDAO dao = fabrica.criarClienteDAO();
//            dao.atualizar(cliente);
//            fabrica.fecharConexao();
//        }
//    }
    
    public  void buscarTodos(){
        clientes.clear();
        fabrica.abrirConexao();
        ClienteDAO dao = fabrica.criarClienteDAO();
//        dao.buscarTodos(quarto);
//        clientes.addAll(quarto.getClientes());
        clientes.addAll(dao.buscarTodos());
        fabrica.fecharConexao();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionar;
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonRemover;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldBusca;
    // End of variables declaration//GEN-END:variables
}
